name: Jest Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run: node -v
    - run: yarn -v
    - uses: actions/checkout@v2
    - name: Use Node.js v12.9.0
      uses: actions/setup-node@v1
      with:
        node-version: '12.9.0'
    - run: yarn
    - run: yarn run test
